#!/bin/sh

setxkbmap -option 'caps:ctrl_modifier'
xcape -e 'Caps_Lock=Escape'

xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation" 1
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Button" 2
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Timeout" 200
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Axes" 6 7 4 5
xinput set-prop "TPPS/2 IBM TrackPoint" "Device Accel Constant Deceleration" 0.95

# TrackPoints only!
xinput set-prop "SynPS/2 Synaptics TouchPad" "Device Enabled" 0

# Make the trackball left+right click == middle-click
xinput set-prop "Primax Kensington Eagle Trackball" "Evdev Middle Button Emulation" 1
# Slow it down a bit, too
xinput set-prop "Primax Kensington Eagle Trackball" "Device Accel Constant Deceleration" 1.5

daemonize $(which dropbox)
